Counting
Niksen111/spbuProgrammingHomeworks pull request #15
Opened 2021-11-02 15:13 UTC by Niksen111

Solving the "Counting" Problem

2021-11-04 17:43 UTC, yurii-litvinov requested changes

2021-11-04 17:43 UTC, yurii-litvinov commented on FifthHomework12.10.21/Stack/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.20)
Непонятно, как тут проектный файл от стека оказался

2021-11-04 17:43 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/circleList.h
> +} CircleList;
Тут уже надо инкапсуляцию навести, перенести полное определение в .c-шник

2021-11-04 17:43 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/circleList.h
> +void switchToN(CircleList** currentPosition, int n);
Комментария нет, и название непонятное

2021-11-04 17:43 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/circleList.c
> +    (*currentPosition) = (*currentPosition)->next;
```suggestion
    *currentPosition = (*currentPosition)->next;
```

2021-11-04 17:43 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/circleList.c
> +}
Ну и, кстати, обратите внимание, что эта функция выражается через другие, так что её можно было и не в модуле со списком делать

2021-11-04 17:43 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/circleList.c
> +        free(deletedPosition);
Незачем, просто free(*currentPosition);. currentPosition же не меняется в этих строчках

2021-11-04 17:43 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/circleList.c
> +        (*currentPosition)->next = NULL;
И это незачем. Мы её сейчас удалим, какая разница, какие у неё поля будут.

2021-11-04 17:43 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/circleList.c
> +        printf("%d ", (list->value));
```suggestion
        printf("%d ", list->value);
```

2021-11-04 17:43 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/circleListTests.c
> +    bool result = (list1->value) == 4;
Тут тоже скобки не нужны

2021-11-04 17:43 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/circleListTests.c
> +    int arrayN[5] = { 3, 5, 5, 14, 10};
```suggestion
    int arrayN[5] = { 3, 5, 5, 14, 10 };
```

2021-11-04 17:43 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/main.c
> +int main() {
```suggestion
int main() 
{
```
CLion так делает, но у нас стайлгайд :) CLion где-то в настройках редактора вроде переубедить можно (иначе им бы никто не пользовался, ведь у каждой компании свои стайлгайды).

2021-11-04 17:43 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/main.c
> +                         int killIndex)
Не выравнивайте отступы, это не переживёт первого же рефакторинга :)

2021-11-04 17:43 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/main.c
> +                (killIndex % numberOfWarriors == 0) - 1;
Что-то сложно. Умножение на булевое значение, что?

2021-11-04 17:43 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/main.c
> +    return ((*myList)->value);
```suggestion
    return (*myList)->value;
```

2021-11-04 17:43 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/main.c
> +    int indexOfSurvivor = giveNumberOfSurvivor(&myList, numberOfWarriors, killIndex);
Это всё-таки не совсем то, что просили. Я хочу передать в функцию два числа и получить число, я не хочу заполнять какой-то список. Ну и тестировать, соответственно, надо эту функцию, с двумя аргументами. Потому как вполне возможно, что всё по отдельности работает правильно, но в main ошибка в подготовке списка — тесты это никак не поймают

2021-11-05 21:16 UTC, Niksen111 commented on SixthHomework19.10.21/Counting/main.c
> +                         int killIndex)
Это не я, честно честно:) CLion шалит

2021-11-07 13:55 UTC, yurii-litvinov requested changes

2021-11-07 13:55 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/circleList.h
> +void switchToN(CircleList** currentPosition, int n);
Тогда уж moveNPositionsForward :)

2021-11-07 13:55 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/circleList.c
> +bool circleListIsEmpty(CircleList** currentPosition)
Функция проверяет утверждение про циклический список в целом, но принимает конкретную позицию (причём зачем-то по двойному указателю). Потому что у Вас список и позиция путаются, что, кстати, архитектурно неправильно, потому что циклический список не обязан быть реализован через указатели. Его тоже можно сделать на массивах, и там позиция будет числом. Как именно представляется позиция --- это дело списка, это нельзя показывать внешнему миру.

2021-11-07 13:55 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/circleList.c
> +    Value returnedValue = ((*currentPosition)->next->value);
```suggestion
    Value returnedValue = (*currentPosition)->next->value;
```

2021-11-07 13:55 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/circleList.c
> +    if ((*currentPosition) == (*currentPosition)->next)
```suggestion
    if (*currentPosition == (*currentPosition)->next)
```

2021-11-07 13:55 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/circleList.c
> +    printf("%d\n", ((*currentPosition)->value));
```suggestion
    printf("%d\n", (*currentPosition)->value);
```

2021-11-07 13:55 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/circleList.c
> +void printCircleList(CircleList** currentPosition)
Проверьте во всех функциях, что по двойному указателю принимаются только позиции, которые мы реально должны менять (причём так, чтобы вызывающий видел изменения).

2021-11-07 13:55 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/main.c
> +                (killIndex % numberOfWarriors == 0) - 1;
Не исправлено и никак не прокомментировано, следовательно задача не зачтена :)

2021-11-07 13:55 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/main.c
> +    int indexOfSurvivor = giveNumberOfSurvivor(numberOfWarriors, killIndex);
```suggestion
    cosnt int indexOfSurvivor = giveNumberOfSurvivor(numberOfWarriors, killIndex);
```

2021-12-03 09:46 UTC, yurii-litvinov approved these changes
Из серьёзных остались только архитектурные замечания, но поскольку их править долго и сейчас это не так важно, зачтена.

2021-12-03 09:46 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/circleList.h
> +Value getCurrentPositionValue(CircleListRoot* root, int *errorCode);
Ну, если Вы думаете, что от переименования CircleList в CircleListRoot стало архитектурно правильнее, то второй семестр будет для Вас полон боли :) Вообще ничего не поменялось, понятия позиции внутри списка и самого списка всё так же не разделены.

2021-12-03 09:46 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/circleList.c
> +    if ((*currentPosition) == NULL)
```suggestion
    if (*currentPosition == NULL)
```

2021-12-03 09:46 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/circleListTests.c
> +bool testswitchRootToNext()
```suggestion
bool testSwitchRootToNext()
```

2021-12-03 09:46 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/circleListTests.c
> +bool testmoveNPositionsForward()
```suggestion
bool testMoveNPositionsForward()
```

2021-12-03 09:46 UTC, yurii-litvinov commented on SixthHomework19.10.21/Counting/main.c
> +    while (myList != getNext(myList, &errorCode1) && errorCode1 == 0)
Побочные эффекты в булевых выражениях не очень, их легко не заметить, поэтому читать программу с ними сложнее. Вообще, есть принцип Command Query Separation, говорящий, что функция либо меняет объект и ничего не возвращает (команда), либо возвращает состояние объекта, но ничего не меняет (запрос).

2021-12-03 19:27 UTC, merged